# Generated by Django 5.0 on 2023-12-13 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='nombre',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='imagen',
            field=models.ImageField(upload_to='trabajadores'),
        ),
    ]
