# Generated by Django 5.0 on 2023-12-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_trabajadores_nombre_alter_trabajadores_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='legajo',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
